resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/shiehn/ci_beach_test.git
    branch: master

jobs:
- name: ci_beach_test
  plan:
  - get: source-code
    trigger: true
  - task: build_source
    file: source-code/build_source_task.yml