---
platform: linux

image_resource:
  type: docker-image
  source: {repository: gradle}

inputs:
- name: source-code
- name: current-app-info

run:
  path: source-code/ci/tasks/smoke-tests.sh
  user: root
