resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/shiehn/ci_beach_test.git
    branch: master

- name: resource-deploy-cf
  type: cf
  source:
    api: https://console.run.pivotal.io
    username: shiehn@pivotal.io
    password: Bivotal7!
    organization: shiehn-org
    space: development
    skip_cert_check: true

jobs:
- name: ci_beach_test
  serial: true
  plan:
  - get: source-code
    trigger: true
  - task: build_source
    file: source-code/ci/build_source_task.yml
  - put: resource-deploy-cf
    inputs:
    - name: backend_build_output
    params:
      manifest: backend_build_output/manifest.yml
      path: backend_build_output/ci_beach_test-0.0.1-SNAPSHOT.jar








