resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/shiehn/ci_beach_test.git
    branch: master

- name: resource-deploy-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: shiehn@pivotal.io
    password: Bivotal7!
    organization: shiehn-org
    space: development
    skip_cert_check: true

jobs:
- name: ci_beach_test
  serial: true
  plan:
  - get: source-code
  - task: build_source_test
    file: source-code/ci/build_source_test.yml
- name: ci_beach_deploy
  plan:
  - get: source-code
    trigger: true
    passed: [ci_beach_test]
  - task: build_source
    file: source-code/ci/build_source_task.yml
  - put: resource-deploy-cf
    params:
      manifest: backend_build_output/manifest.yml
      path: backend_build_output/source-code-0.0.1-SNAPSHOT.jar








